version: '3.7'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_INITDB_DATABASE=amazona
    volumes:
      - ./../../data/db:/data/db
    ports:
      - 27017:27017
